require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProductsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Product. As you add validations to Product, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for :product, name: 'book'
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  it { is_expected.to use_before_action(:authenticate_user!) }
  it { is_expected.to use_before_action(:authorize!) }

  describe "GET #index" do
    it "assigns all products as @products" do
      product = Product.create! valid_attributes
      products = [product]
      expect(Product).to receive(:for).with(controller.current_user).and_return(products)

      process :index, method: :get
      expect(assigns(:products)).to eq(products)
    end
  end

  describe "GET #show" do
    it "assigns the requested product as @product" do
      product = Product.create! valid_attributes
      process :show, method: :get, params: {id: product.to_param}
      expect(assigns(:product)).to eq(product)
    end
  end

  describe "GET #new" do
    it "assigns a new product as @product" do
      process :new, method: :get
      expect(assigns(:product)).to be_a_new(Product)
    end
  end

  describe "GET #edit" do
    it "assigns the requested product as @product" do
      product = Product.create! valid_attributes
      process :edit, method: :get, params: {id: product.to_param}
      expect(assigns(:product)).to eq(product)
    end
  end

  describe "POST #create" do
    before(:each) do
      user = FactoryGirl.create :user
      expect(controller).to receive(:current_user).and_return(user)
    end

    it 'permited params' do
      params = {
        product: {
          name: ''
        }
      }
      is_expected.to permit(:name).for(:create, params: params).on(:product)
    end

    it 'unpermited params' do
      params = {
        product: {
          user_id: ''
        }
      }
      is_expected.not_to permit(:user_id).for(:create, params: params).on(:product)
    end

    context "with valid params" do
      it "creates a new Product" do
        expect {
          process :create, method: :post, params: {product: valid_attributes}
        }.to change(Product, :count).by(1)
      end

      it "assigns a newly created product as @product" do
        process :create, method: :post, params: {product: valid_attributes}
        expect(assigns(:product)).to be_a(Product)
        expect(assigns(:product)).to be_persisted
      end

      it "redirects to the created product" do
        process :create, method: :post, params: {product: valid_attributes}
        expect(response).to redirect_to(Product.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved product as @product" do
        process :create, method: :post, params: {product: invalid_attributes}
        expect(assigns(:product)).to be_a_new(Product)
      end

      it "re-renders the 'new' template" do
        process :create, method: :post, params: {product: invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do

    it 'permited params' do
      product = Product.create! valid_attributes
      params = {
        id: product.id,
        product: {
          name: ''
        },
      }
      is_expected.to permit(:name).for(:update, params: params).on(:product)
    end

    it 'unpermited params' do
      product = Product.create! valid_attributes
      params = {
        id: product.id,
        product: {
          user_id: ''
        }
      }
      is_expected.not_to permit(:user_id).for(:update, params: params).on(:product)
    end

    context "with valid params" do
      let(:new_attributes) {
        {name: "Pencil"}
      }

      it "updates the requested product" do
        product = Product.create! valid_attributes
        process :update, method: :put, params: {id: product.to_param, product: new_attributes}
        product.reload
        expect(product.name).to eq "Pencil"
      end

      it "assigns the requested product as @product" do
        product = Product.create! valid_attributes
        process :update, method: :put, params: {id: product.to_param, product: valid_attributes}
        expect(assigns(:product)).to eq(product)
      end

      it "redirects to the product" do
        product = Product.create! valid_attributes
        process :update, method: :put, params: {id: product.to_param, product: valid_attributes}
        expect(response).to redirect_to(product)
      end
    end

    context "with invalid params" do
      it "assigns the product as @product" do
        product = Product.create! valid_attributes
        process :update, method: :put, params: {id: product.to_param, product: invalid_attributes}
        expect(assigns(:product)).to eq(product)
      end

      it "re-renders the 'edit' template" do
        product = Product.create! valid_attributes
        process :update, method: :put, params: {id: product.to_param, product: invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested product" do
      product = Product.create! valid_attributes
      expect {
        process :destroy, method: :delete, params: {id: product.to_param}
      }.to change(Product, :count).by(-1)
    end

    it "redirects to the products list" do
      product = Product.create! valid_attributes
      process :destroy, method: :delete, params: {id: product.to_param}
      expect(response).to redirect_to(products_url)
    end
  end

end
